### PR TITLE
UMT coordinates

### PR DESCRIPTION
**Pull request by malaclemys**
Now you can input UTM coordinates. Add some new functions, see examples.

### CODE REVIEW

**Comment by tcassou** [comment]
Thanks @malaclemys & @jquintas for the suggestion.
- for some reason I see changes twice for `mapsplot.py` and `google_static_maps_api.py`, could you clean that up?
- what are the xml files in the PR meant for? The binary file?

Overall there's quite a lot of things going on here, not all related to UTM coordinates (some python 3 syntax, option to save files, changes in existing methods, etc) and some fairly long methods (ex `scatter_with_wgs84`, number of lines went > 3 fold), and
1. I'd like to keep all of them in separate issues or PR
2. as much as possible I'd like to avoid mixing logics of the plotting part (`mapsplot`) and the Google Maps part (`google_static_maps_api` which does all conversions, etc).

So would be great if you could open smaller issues/PR so we take it one step at a time.
Thanks again!

**Comment by malaclemys** [comment]
Hello tcassou
Yeah I can clean up the things a little bit. The xml files for example are totally unnecessary. 
The double changes I think is because I changed the files in the mapsplotlib folder and outside where the README is, maybe this is not necessary.

I agree with you about the amount of changes, they might be overwhelming for starting. I will open smaller PRs to be easier for you. 
Please tell me if you are interested in some of the changes?

So my main goal is to be able to plot and return a google static map of a certain area but with the x-axis and y-axis tick values using the correct coordinate values and not in meters from 0 to some value. Afterwards with the output figure I can plot some more information using real coordinates. I think this could be a good starting point.

Thanks,

**Comment by tcassou** [comment]
- Python 3 compatibility is definitely nice to have (I've developed it under python 2.7),
- saving images why not, though from a notebook it's easy to do it manually. If the changes are minimalistic I'm open to it
- never worked with UTM coordinates, sounds like a good feature, ideally I'd like to make the code smart (while retro compatible) to avoid duplicating all plotting methods depending on the coordinates.

**Comment by tcassou** [comment]
I'll close this for lack of activity, feel free to reopen if you want to discuss further, thanks!

**Pull request closed without merging**
